### ISSUE TITLE
"no tests ran" when integrating with Saucelabs

### ISSUE THREAD

**Issue by andrey-p** [defunctzombie/zuul#118]
I followed the [wiki guidelines](https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for setting up Saucelabs (open source account).

Running `zuul -- test/*` gives me `no tests ran` - whereas `zuul --ui mocha-bdd --local -- test/*` and visiting the URL gets 18 tests passing as expected.

Contents of `.zuul.yml`:

``` yml
ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
    platform: Windows 7
  - name: safari
    version: latest
    platform: OS X 10.10
  - name: firefox
    version: latest
    platform: Windows 7
  - name: ie
    version: 6..8
    platform: Windows XP
  - name: ie
    version: 9..11
    platform: Windows 7
```

And my `~/.zuulrc`:

```
sauce_username: pissanchev
sauce_key: [redacted]
```

Hope I'm not missing something too obvious...
