### ISSUE TITLE
How to pass options to Browserify transform?

### ISSUE THREAD

**Issue by pheuter** [defunctzombie/zuul#141]
In **.zuul.yml**, I want to be able to pass options to a particular transform, like so:

```yaml
browserify:
  - transform: [ reactify --es6 ]
  - transform: concatenify
```

I've tried using different syntax, including an `-options` entry, but none seem to work.

**Comment by defunctzombie** [comment]
I don't think this is currently supported. How do you pass options to transforms on the browserify command line?

**Comment by rase-** [comment]
@defunctzombie like so:
```
-t [6to5ify --blacklist react]
```

**Comment by rase-** [comment]
I can look into it.

**Comment by rase-** [comment]
Submitted https://github.com/defunctzombie/zuul/pull/143

Looking into browserify's `_mdeps.transforms` it looks good, but I haven't tried the options in practice. Creating a test project to try it out.

**Comment by rase-** [comment]
Tried successfully with a small transform:

```
var through = require('through2');

module.exports = function (file, opts) {
    return through(function (buf, enc, next) {
        this.push(buf.toString('utf8') + '/* comment ' + opts.custom + '*/');
        next();
    });
};
```

```
browserify:
  - transform:
      name: testify
      custom: this should appear
  - transform: 6to5ify
```
