### ISSUE TITLE
Local: getaddrinfo ENOTFOUND localhost localhost:64471

### ISSUE THREAD

**Issue by bfred-it** [defunctzombie/zuul#276]
Opening zuul locally causes it to fail

```
$ zuul --local 8080 -- tests/index.js
open the following url in a browser:
http://localhost:8080/__zuul
```
Then I open the page (which fails to load) and:

```
/usr/local/lib/node_modules/zuul/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: getaddrinfo ENOTFOUND localhost localhost:64471
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

This is my `.zuul.yml` file but it doesn't seem to make any difference:

```yml
ui: tape
browsers:
  - name: chrome
    version: latest
    platform: Mac 10.11
```

Same here, I tried v0.12 too

```
$ node -v
v5.7.1
```
