### ISSUE TITLE
zuul@1.1.0 does not serves - scripts

### ISSUE THREAD

**Issue by vvo** [defunctzombie/zuul#28]
Given this project : https://github.com/vvo/in-viewport

``` yaml
ui: mocha-bdd
html: test/fixtures/template.html
scripts:
  - build/in-viewport.min.js
browsers:
  - name: chrome
    version: 29..latest
  - name: firefox
    version: 24..latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: 5.0..latest
  - name: ipad
    version: 5.0..latest
```

When starting zuul locally:

``` bash
zuul --local 8080 -- test/*.js
```

It hangs forever because it tries to load `http://localhost:8080/build/in-viewport.min.js` and does not find it.

`zuul@1.0.10` does not have this problem.
