### ISSUE TITLE
Chrome tests suddenly running on every platform

### ISSUE THREAD

**Issue by feross** [defunctzombie/zuul#78]
Noticed recently that with this config

``` yaml
ui: tape
browsers:
  - name: chrome
    version: 35..latest
  - name: firefox
    version: 30..latest
```

that Chrome tests are running on every possible platform. See:

![screen shot 2014-09-13 at 5 37 29 pm](https://cloud.githubusercontent.com/assets/121766/4261218/50ff2816-3b64-11e4-9adb-4bc13b37720b.png)

This didn't used to happen before, and doesn't happen with Firefox tests. Maybe the browser json endpoint changed?
