### ISSUE TITLE
Versions are messed up again

### ISSUE THREAD

**Issue by feross** [defunctzombie/zuul#79]
Haven't had time to investigate yet, but with:

``` yaml
ui: tape
browsers:
  - name: chrome
    version: 35..latest
  - name: firefox
    version: 30..latest
```

I'm getting:

![screen shot 2014-09-27 at 12 38 44 am](https://cloud.githubusercontent.com/assets/121766/4429761/475afab4-4600-11e4-8205-e85a1d1acf7d.png)

Before I killed it. I've seen other variations on this issue recently, as well.
